name: ci

on:
  push:
    # only pushes to main trigger
    branches: [main]
  pull_request:
    # always triggered

jobs:

  tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12', '3.13']
        aiida-version: ['stable']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install hatch
      run: |
        pip install --upgrade pip
        pip install hatch
    - name: Install Graphviz
      run: sudo apt-get install graphviz graphviz-dev
    - name: Set up SSH on localhost
      run: |
        # Start SSH daemon
        sudo systemctl start ssh

        ssh-keygen -q -t rsa -b 4096 -N "" -f "${HOME}/.ssh/id_rsa"
        ssh-keygen -y -f "${HOME}/.ssh/id_rsa" >> "${HOME}/.ssh/authorized_keys"
        ssh-keyscan -H localhost >> "${HOME}/.ssh/known_hosts"

        # The permissions on the GitHub runner are 777 which will cause SSH to refuse the keys and cause authentication to fail
        chmod 755 "${HOME}"

        # Test SSH connection
        ssh -o StrictHostKeyChecking=no localhost 'echo "SSH connection successful"'
    - name: Install package
      run: |
        pip install .
        verdi presto
    - name: Run test suite
      env:
        PYTEST_ADDOPTS: "--durations=0"
      run: |
        hatch test -- -m 'not requires_icon' -s --remote localhost-ssh -k test_run_workgraph tests/test_wc_workflow.py

  docs:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install hatch
      run: |
        pip install --upgrade pip
        pip install hatch
    - name: Install Graphviz
      run: sudo apt-get install graphviz graphviz-dev
    - name: Install package
      run: |
        pip install .
        verdi presto
    - name: Build docs
      run: hatch run docs:build

  fmt:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install hatch
      run: |
        pip install --upgrade pip
        pip install hatch
    - name: Install Graphviz
      run: sudo apt-get install graphviz graphviz-dev
    - name: Install package
      run: |
        pip install .
        verdi presto
    - name: Run formatter and linter
      run: hatch fmt --check

  typechecking:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v5
      with:
        python-version: 3.12
    - name: Install hatch
      run: |
        pip install --upgrade pip
        pip install hatch
    - name: Install Graphviz
      run: sudo apt-get install graphviz graphviz-dev
    - name: Run formatter and linter
      run: hatch run types:check
